### PR TITLE
Fixes/issues 47 48

### LINKED ISSUE #47: On add member, does not save tag
When adding a member, the choice of tag is not saved

### PR DESCRIPTION
**Pull request by verdonarthur**
- We can set club member now
- MemberLabels are also saved on new member creation

Resolved #47 and #48

### CODE REVIEW

File: packages/frontend/src/components/organisms/MemberForm.tsx [hunk 1]
```diff
@@ -30,38 +35,51 @@ interface IProps {
...
     },
     global: '',
   };
 
   if (props.member) {
     initialValues.memberLabels =
       props.member.memberLabels?.map((label) => label.id) || [];
+    initialValues.club = props.member.club?.id;
     initialValues.user = { ...initialValues.user, ...props.member.user };
+    console.log(initialValues);
```
Comment (sebibigbob8) [inline packages/frontend/src/components/organisms/MemberForm.tsx:67]: Is that useful?

**Review by sebibigbob8 — CHANGES_REQUESTED** [review]
